manifest:
  remotes:
    - name: nmunnich
      url-base: https://github.com/nmunnich
  projects:
    - name: zmk
      remote: nmunnich
      revision: layer-locking
      import: app/west.yml
  self:
    path: config